# -*- coding: utf-8 -*-
"""Koopman_pendullum_attempt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RaLiV2ZgbBva3kytdyxoU3X2vOETP0vr
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt

# generating the data for the model training
def generate_pendulum_data(N=2000, T=20, dt=0.1):
    a = 9.8
    n_steps = int(T / dt)

    # ODE function: x[0] = angle, x[1] = angular velocity
    def ode_fun(t, x):
        return [x[1], -a * np.sin(x[0])]

    X_data = []
    Y_data = []

    for _ in range(N):
        # random initial conditions: x[0] in [-pi/4, pi/4], x[1] in [-1.5, 1.5]
        x0 = [np.random.uniform(-np.pi/4, np.pi/4), np.random.uniform(-1.5, 1.5)]
        t_span = np.linspace(0, T, n_steps + 1)
        sol = solve_ivp(ode_fun, [0, T], x0, t_eval=t_span)

        # x_t (X) and x_{t+1} (Y)
        x_ode = sol.y.T # Shape (n_steps+1, 2)
        X_data.append(x_ode[:-1, :])
        Y_data.append(x_ode[1:, :])

    return torch.tensor(np.vstack(X_data), dtype=torch.float32), \
           torch.tensor(np.vstack(Y_data), dtype=torch.float32)

# defining the model
class KoopmanAutoencoder(nn.Module):
    def __init__(self, I_d=2, L_d=12):
        super(KoopmanAutoencoder, self).__init__()

        # Encoder: x -> psi(x)
        self.encoder = nn.Sequential(
            nn.Linear(I_d, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, L_d)
        )

        # Decoder: psi(x) -> x
        self.decoder = nn.Sequential(
            nn.Linear(L_d, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, I_d)
        )

        # Koopman Operator K: psi(x_{t+1}) = K * psi(x_t)
        # representing K as a simple linear layer without bias
        self.K = nn.Linear(L_d, L_d, bias=False)

    def forward(self, x_t, x_next):
        # lift to latent space
        psi_t = self.encoder(x_t)
        psi_next_pred = self.K(psi_t) # K applied to latent state

        # Decode back to physical space
        x_t_hat = self.decoder(psi_t)
        x_next_hat = self.decoder(psi_next_pred)

        # Actual lifting of the next state for prediction loss
        psi_next_actual = self.encoder(x_next)

        return x_t_hat, x_next_hat, psi_next_pred, psi_next_actual

# training setup and the training loop
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X, Y = generate_pendulum_data(N=1000)
dataset = torch.utils.data.TensorDataset(X, Y)
loader = torch.utils.data.DataLoader(dataset, batch_size=256, shuffle=True)

model = KoopmanAutoencoder(L_d=8).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
criterion = nn.MSELoss()

epochs = 120
for epoch in range(epochs):
    total_loss = 0
    for batch_x, batch_y in loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        x_hat, x_next_hat, psi_next_pred, psi_next_actual = model(batch_x, batch_y)

        # Loss 1: Reconstruction Loss ||x - dec(enc(x))||
        loss_rec = criterion(x_hat, batch_x)

        # Loss 2: Prediction Loss ||dec(K * enc(x)) - x_next||
        loss_pred = criterion(x_next_hat, batch_y)

        # Loss 3: Linearity Loss ||K * enc(x) - enc(x_next)||
        loss_lin = criterion(psi_next_pred, psi_next_actual)

        loss = loss_rec + loss_pred + 0.1*loss_lin

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    if (epoch+1) % 10 == 0:
        print(f"Epoch {epoch+1}, Loss: {total_loss/len(loader):.6f}")

# extract the koopman operator (the K matrix)
# The weights of the self.K layer represent the Koopman Matrix K^T
K_matrix = model.K.weight.detach().cpu().numpy()
print("\nExtracted Koopman Operator (K):")
print(K_matrix)

# 6. TRAJECTORY COMPARISON: ODE vs KOOPMAN
model.eval() # Set to evaluation mode

# Define initial condition and time parameters
x0_test = torch.tensor([[np.pi/4, 0.0]], dtype=torch.float32).to(device)
T_test = 20
dt = 0.1
steps = int(T_test / dt)

# generating an actual trajectory using the ODE function
def ode_fun(t, x):
    return [x[1], -9.8 * np.sin(x[0])]

t_span = np.linspace(0, T_test, steps + 1)
from scipy.integrate import solve_ivp
sol = solve_ivp(ode_fun, [0, T_test], x0_test.cpu().numpy().flatten(), t_eval=t_span)
actual_velocity = sol.y[1, :] # Extracting Velocity (x2)

# generating a predicted trajectory using the learned kK matrix
predicted_velocity = []
with torch.no_grad():
    # Lift the initial condition to the latent space
    curr_psi = model.encoder(x0_test)

    for _ in range(steps + 1):
        # Decode the current latent state to get physical velocity
        x_hat = model.decoder(curr_psi)
        predicted_velocity.append(x_hat[0, 1].item()) # Index 1 is velocity

        # Advance the latent state using the Koopman Operator K
        curr_psi = model.K(curr_psi)

# plot them for comparision
plt.figure(figsize=(10, 5))
plt.plot(t_span, actual_velocity, 'b-', label='Actual Velocity ', linewidth=2)
plt.plot(t_span, predicted_velocity, 'r--', label='Predicted Velocity ', linewidth=2)
plt.xlabel('Time')
plt.ylabel('Velocity')
plt.title('Velocity Comparison: ACtual trajectory vs. Predicted trajectory')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()